// Auto-generated by LibreLane
module adder16(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input clk,
  input rst_n,
  input en,
  input[15:0] a,
  input[15:0] b,
  output[15:0] sum,
  output carry
);
endmodule
